### ISSUE TITLE
(suggestion/concept) Bluetooth connectivity

### ISSUE THREAD

**Issue by slrdur** [strunker/GoveeSync#1]
Is it possible to make this program connect through bluetooth, and how?

**Comment by strunker** [comment]
I dont believe so. For a number of reasons. For starters Govee doesnt publicy disclose, nor support, any other APIs except for the public reset interface (which uses TCP), and the internal lan api (which uses UDP). In order to make this somehow work over BT we would need to see if we could send UDP packets over bluetooth to the device and then somehow hit its internal webserver, something I have never done nor would know how to do. One option could be to sniff the bluetooth traffic using wireshark and see if you could emulate the app controls over bluetooth to the device. That wold bypass the internal Lan api, and just kind emulate what the Govee mobile app does over BT. 
Im not sure what you use case is, but all their newer products support wifi/the internal lan udp api.
