### ISSUE TITLE
Documentation for LAN commands

### ISSUE THREAD

**Issue by StevenKauwe** [strunker/GoveeSync#2]
It looks like you are using some commands that aren't in the released LAN API for Govee products. I'd love to learn how you found this functionality.

**Comment by strunker** [comment]
Hi Steven,
This [thread ](https://www.reddit.com/r/Govee/comments/15adz3b/can_the_govee_curtain_lights_be_controlled_by_the/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) has tons of info in it if you want to dive into some of the research there. In short though, I noticed their desktop application had the ability to control LED segments while their API docs never alluded to this ability (as you said). So I essentially, using a mix of tools (procmon, wireshark, dotPeek) reverse engineered their desktop application. I had been in talks with Govee for a year + over email since I had discovered the /razer endpoint a long time ago, back when they started their work with razer the company [around two years ago](https://9to5toys.com/2022/07/06/govee-razer-integration/). They kept saying they would release it, and add it to the docs, and they never did, so here we are. Hope this answers this question.

**Comment by strunker** [comment]
Gonna close this out, if you need any additional info open a specific issue please. ty.
